# Generated by Django 4.2.5 on 2023-09-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('hint', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Diagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('datos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAlternativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_preguntas', models.IntegerField(default=3)),
                ('tema', models.CharField(max_length=100)),
                ('pregunta_actual', models.IntegerField(default=1)),
                ('dificultad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('dificultad', models.IntegerField(default=0)),
                ('enunciado', models.CharField(max_length=1000)),
                ('variables_calcular_json', models.TextField()),
                ('hint', models.CharField(max_length=1000)),
                ('diagrama', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.diagrama')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=1000)),
                ('respuesta_correcta', models.CharField(max_length=1)),
                ('alternativas', models.ManyToManyField(blank=True, to='tasks.alternativa')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='preguntaalternativas',
            name='preguntas_correctas',
            field=models.ManyToManyField(blank=True, related_name='preguntas_correctas_rel', to='tasks.preguntaindividual'),
        ),
        migrations.AddField(
            model_name='preguntaalternativas',
            name='preguntas_incorrectas',
            field=models.ManyToManyField(blank=True, related_name='preguntas_incorrectas_rel', to='tasks.preguntaindividual'),
        ),
    ]
