# Generated by Django 4.2.5 on 2023-09-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alternativa_diagrama_estudiante_preguntaalternativas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaalternativas',
            name='preguntas',
            field=models.ManyToManyField(blank=True, related_name='preguntas', to='tasks.preguntaindividual'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='hint',
            field=models.CharField(max_length=10000),
        ),
    ]
