# Generated by Django 4.2.5 on 2023-09-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_preguntaalternativas_preguntas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaindividual',
            name='respuesta_correcta',
            field=models.CharField(max_length=3),
        ),
    ]
