# Generated by Django 4.2.5 on 2023-09-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_preguntaindividual_respuesta_correcta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaalternativas',
            name='preguntas_correctas',
            field=models.ManyToManyField(blank=True, null=True, related_name='preguntas_correctas_rel', to='tasks.preguntaindividual'),
        ),
        migrations.AlterField(
            model_name='preguntaalternativas',
            name='preguntas_incorrectas',
            field=models.ManyToManyField(blank=True, null=True, related_name='preguntas_incorrectas_rel', to='tasks.preguntaindividual'),
        ),
    ]
