# Generated by Django 4.2.5 on 2023-09-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_preguntaindividual_alternativas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntaalternativas',
            name='preguntas_correctas',
        ),
        migrations.RemoveField(
            model_name='preguntaalternativas',
            name='preguntas_incorrectas',
        ),
        migrations.AddField(
            model_name='preguntaalternativas',
            name='cantidad_correctas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preguntaindividual',
            name='esta_correcta',
            field=models.BooleanField(default=False),
        ),
    ]
